### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by benjamishirley** [Crisicus/maestro_mcz#48]
Integration stopped working between 21 / 22 May. I remember the Maestro MCZ App on my phone mentioning some upcomming server updates on MCZ side a few days ago. I'm keeping my fingers crossed this is not a to big of a problem.

Thanks for making this integration available to me :-)

Benjamin

![grafik](https://github.com/Crisicus/maestro_mcz/assets/52283703/382bb78b-b081-4400-9115-03d92b4a7f50)

**Comment by Robbe-B** [comment]
Hi @benjamishirley, can you check the logging for errors ?

**Comment by Robbe-B** [comment]
You can always roll back to the last version where it was still working and provide me the diagnostics file :)

**Comment by benjamishirley** [comment]
Hi @Robbe-B, good to know it seeme to be a problem on my end. It just stopped working today - it worked yesterday. I did not change / update in the meantime.  There is not a lot in the home assistant logs, I enabled Debug Logging for the integration and get this output: 

`Error setting up entry xxx@xxx.com for maestro_mcz

Traceback (most recent call last):
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 80, in Login
    async with session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/maestro_mcz/__init__.py", line 35, in async_setup_entry
    await maestroapi.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 67, in MakeRequest
    await self.Login()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 87, in Login
    await self.StoveInfo()
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 92, in StoveInfo
    res = await self.MakeRequest(
  File "/config/custom_components/maestro_mcz/maestro/__init__.py", line 45, in MakeRequest
    async with async_timeout.timeout(15):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
`

**Comment by benjamishirley** [comment]
I can delete and reconfigure the integration if you recommend to do so.

**Comment by Robbe-B** [comment]
I would try that indeed.
From what I see in the debug logging, it seems you can't login anymore.

**Comment by Robbe-B** [comment]
From what I can see in my own logging there was a timeout period of the MCZ servers last night.
Did you try to restart home assistant ?

**Comment by benjamishirley** [comment]
I restarted home assistant this morning, which did not resolve the issue. Will try re-setting up the integration now.

**Comment by Robbe-B** [comment]
After a restart of my home assistant instance, I have the same behavior as you. 
I'll look into this as soon as I have the time.

**Comment by benjamishirley** [comment]
Thanks a lot @Robbe-B . I tried re-configuring the integration with no luck.

**Comment by Robbe-B** [comment]
FYI, as soon as I try to access the more advanced settings and stuff in the MCZ app, it isn't working either. I think they again released a non-tested api at there side.

**Comment by Robbe-B** [comment]
@Crisicus, 
To me it seems that MCZ changed this url => https://s.maestro.mcz.it/hlapi/v1.0/Nav/Auth/FirstVisibleObjects
It returns always "404 Not Found".
Can you easily check what the replacement URL is ?

**Comment by Robbe-B** [comment]
@benjamishirley, 
Issue should be solved by installing [v0.3.5-beta](https://github.com/Crisicus/maestro_mcz/releases/tag/v0.3.5-beta)

**Comment by benjamishirley** [comment]
@Robbe-B  done ✅ 

I was able to setup my stove and it seems to be working!  THANKS for that quick fix!
